name: Publish WorkFlow

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 🦾 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: 🚀 Publish to PyPi
        env: 
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_TEST_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}

        run: |
          python setup.py sdist bdist_wheel
          twine upload -r testpypi dist/* -u $TWINE_USERNAME -p $TWINE_TEST_PASSWORD --verbose 
          twine check dist/*
          twine upload dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD --verbose 